import Foundation
import SwiftData

/// Extensions to Card model for ER-0008, ER-0009, and ER-0010
/// These properties will be added in schema migrations (AppSchemaV6, V7, etc.)
///
/// NOTE: This file documents the NEW properties that will be added.
/// Actual implementation requires schema migration in Migrations.swift

// MARK: - ER-0008: Timeline System Properties

extension Card {

    // MARK: Timeline-Specific Properties

    /// Calendar system used by this timeline (for Timeline cards only)
    /// Relationship to CalendarSystem model
    /// Added in: AppSchemaV6
    ///
    /// var calendarSystem: CalendarSystem?

    /// Epoch date - the starting point/zero-date for this timeline
    /// For Timeline cards only
    /// Added in: AppSchemaV6
    ///
    /// var epochDate: Date?

    /// Human-readable description of the epoch
    /// Example: "The beginning of the Age of Starlight"
    /// For Timeline cards only
    /// Added in: AppSchemaV6
    ///
    /// var epochDescription: String?

    // Note: Scene temporal positioning is handled in CardEdge extensions below
}

// MARK: - ER-0009: AI Image Generation Properties

extension Card {

    // MARK: AI Image Metadata

    /// Whether the card's image was generated by AI
    /// Added in: AppSchemaV7
    ///
    /// var imageGeneratedByAI: Bool?

    /// AI provider used to generate the image
    /// Example: "Apple Intelligence", "OpenAI (ChatGPT)"
    /// Added in: AppSchemaV7
    ///
    /// var imageAIProvider: String?

    /// Original prompt used to generate the image
    /// Added in: AppSchemaV7
    ///
    /// var imageAIPrompt: String?

    /// Timestamp when the image was generated
    /// Added in: AppSchemaV7
    ///
    /// var imageAIGeneratedAt: Date?

    // MARK: Regeneration History

    /// Previous versions of AI-generated images (external storage)
    /// Stores up to N previous versions (configurable, default 5)
    /// Added in: AppSchemaV7
    ///
    /// @Attribute(.externalStorage)
    /// var imageHistoryData: Data?

    /// Metadata about previous image versions
    /// Added in: AppSchemaV7
    ///
    /// var imageHistoryMetadata: [ImageHistoryEntry]?
}

// MARK: - Image History Entry

/// Metadata for a previous version of an AI-generated image
/// Stored in Card.imageHistoryMetadata
struct ImageHistoryEntry: Codable, Identifiable {
    var id = UUID()

    /// Timestamp when this version was generated
    var timestamp: Date

    /// Provider used for this version
    var provider: String

    /// Prompt used for this version
    var prompt: String

    /// Version number (1, 2, 3, ...)
    var version: Int

    /// Size of the image data in bytes
    var sizeBytes: Int
}

// MARK: - ER-0008: CardEdge Temporal Positioning

/// Extensions to CardEdge for temporal positioning of scenes on timelines
/// These properties will be added in schema migration (AppSchemaV6)
extension CardEdge {

    // MARK: Temporal Positioning

    /// Temporal position of a scene on a timeline
    /// Used when timeline has a calendar system (temporal mode)
    /// Added in: AppSchemaV6
    ///
    /// var temporalPosition: Date?

    /// Duration of the scene (in seconds)
    /// Used for visualizing scene length on timeline
    /// Added in: AppSchemaV6
    ///
    /// var duration: TimeInterval?

    // Note: Existing sortIndex property is preserved for backward compatibility
    // Ordinal timelines (without calendar) continue using sortIndex
    // Temporal timelines use temporalPosition + duration

    /// Detect whether this edge uses temporal or ordinal positioning
    /// Returns true if temporalPosition is set, false if using sortIndex
    /// Added in: AppSchemaV6
    ///
    /// var usesTemporal Positioning: Bool {
    ///     temporalPosition != nil
    /// }
}

// MARK: - Helper Methods for AI Image Generation

extension Card {

    /// Check if this card should auto-generate an image
    /// Based on user settings and card state
    func shouldAutoGenerateImage() -> Bool {
        // Check user preference
        guard UserDefaults.standard.bool(forKey: "aiGeneration_autoGenerate") else {
            return false
        }

        // Check conditions
        let hasNoImage = originalImageData == nil
        let hasDescription = !(detailedText.isEmpty)
        let wordCount = detailedText.split(separator: " ").count
        let minWords = UserDefaults.standard.integer(forKey: "aiGeneration_autoGenerateMinWords")
        let meetsMinimum = wordCount >= (minWords > 0 ? minWords : 50)

        return hasNoImage && hasDescription && meetsMinimum
    }

    /// Get AI attribution text for display
    /// Returns formatted attribution string if image was AI-generated
    func aiAttributionText() -> String? {
        guard let provider = imageAIProvider,
              let generatedAt = imageAIGeneratedAt else {
            return nil
        }

        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        formatter.timeStyle = .short

        return "Generated by \(provider) on \(formatter.string(from: generatedAt))"
    }

    /// Check if image history is available
    var hasImageHistory: Bool {
        guard let metadata = imageHistoryMetadata else { return false }
        return !metadata.isEmpty
    }

    /// Get count of previous image versions
    var imageHistoryCount: Int {
        imageHistoryMetadata?.count ?? 0
    }
}

// MARK: - Helper Methods for Timeline System

extension Card {

    /// Check if this card is a timeline with a calendar system
    var isTemporalTimeline: Bool {
        kind == .timelines && calendarSystem != nil
    }

    /// Check if this card is an ordinal timeline (no calendar)
    var isOrdinalTimeline: Bool {
        kind == .timelines && calendarSystem == nil
    }

    /// Get formatted epoch description for display
    func formattedEpochDescription() -> String {
        if let description = epochDescription, !description.isEmpty {
            return description
        }

        if let date = epochDate {
            let formatter = DateFormatter()
            formatter.dateStyle = .long
            formatter.timeStyle = .none
            return formatter.string(from: date)
        }

        return "No epoch defined"
    }

    /// Validate timeline configuration
    /// Returns nil if valid, error message if invalid
    func validateTimelineConfiguration() -> String? {
        guard kind == .timelines else {
            return nil // Not a timeline, no validation needed
        }

        // If calendar is set, epoch should also be set
        if calendarSystem != nil && epochDate == nil {
            return "Timeline with calendar system requires an epoch date"
        }

        // Validate calendar system if present
        if let calendar = calendarSystem {
            return calendar.validate()
        }

        return nil // Valid
    }
}

// MARK: - Helper Methods for Scene Temporal Positioning

extension CardEdge {

    /// Get display position for a scene on a timeline
    /// Returns temporal position if available, otherwise falls back to sortIndex
    var displayPosition: Any {
        if let temporal = temporalPosition {
            return temporal
        }
        return sortIndex
    }

    /// Check if this edge represents a temporal scene placement
    var isTemporalPlacement: Bool {
        temporalPosition != nil
    }

    /// Format temporal position for display
    func formattedTemporalPosition(calendar: CalendarSystem?) -> String? {
        guard let position = temporalPosition else {
            return nil
        }

        let formatter = DateFormatter()

        if let calendar = calendar {
            // TODO: Format using custom calendar divisions
            // For now, use standard date formatting
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
        } else {
            formatter.dateStyle = .medium
            formatter.timeStyle = .short
        }

        return formatter.string(from: position)
    }

    /// Format duration for display
    func formattedDuration() -> String? {
        guard let duration = duration, duration > 0 else {
            return nil
        }

        let formatter = DateComponentsFormatter()
        formatter.unitsStyle = .abbreviated
        formatter.allowedUnits = [.day, .hour, .minute]
        formatter.maximumUnitCount = 2

        return formatter.string(from: duration)
    }
}

// MARK: - Schema Migration Notes

/*
 These properties will be added through schema migrations:

 AppSchemaV6 (ER-0008):
 - Card.calendarSystem: CalendarSystem?
 - Card.epochDate: Date?
 - Card.epochDescription: String?
 - CardEdge.temporalPosition: Date?
 - CardEdge.duration: TimeInterval?

 AppSchemaV7 (ER-0009):
 - Card.imageGeneratedByAI: Bool?
 - Card.imageAIProvider: String?
 - Card.imageAIPrompt: String?
 - Card.imageAIGeneratedAt: Date?
 - Card.imageHistoryData: Data?
 - Card.imageHistoryMetadata: [ImageHistoryEntry]?

 Migration implementation will be in Migrations.swift following the pattern
 established for AppSchemaV1 through AppSchemaV5.

 All properties are optional to support:
 1. CloudKit sync requirements (all relationships must be optional)
 2. Backward compatibility (existing cards don't have these properties)
 3. Forward compatibility (not all card kinds use all properties)
 */
