//
//  Card.swift
//  Cumberland
//
//  Created by Mike Stoddard on 10/1/25.
//

import Foundation
import SwiftData
import SwiftUI
import CoreGraphics
import ImageIO
import UniformTypeIdentifiers
import CoreTransferable

// Persistence model notes:
// - id is unique to support stable identity across sync and devices.
// - We index key string fields to speed up searches and sorts.
// - thumbnailData uses external storage to keep row payloads small; it remains synced.
// - originalImageData uses external storage so SwiftData/CloudKit can store it efficiently (CKAsset).
// - imageFileURL is a local cache path only (not synced).
//
@Model
final class Card: Identifiable {
    // Stable identifier for selection and hashing (CloudKit: provide default)
    var id: UUID = UUID()

    // Persisted primitive backing for Kind (CloudKit-safe)
    // Use computed 'kind' for app logic.
    var kindRaw: String = Kinds.projects.rawValue

    // Core fields (CloudKit: provide defaults)
    var name: String = "" {
        didSet { recomputeNormalizedSearchText() }
    }

    var subtitle: String = "" {
        didSet { recomputeNormalizedSearchText() }
    }

    var detailedText: String = "" {
        didSet { recomputeNormalizedSearchText() }
    }

    // Optional author field
    // Provide a default so migration can backfill existing rows.
    var author: String? = nil {
        didSet { recomputeNormalizedSearchText() }
    }

    // Persisted primitive backing for SizeCategory (CloudKit-safe)
    var sizeCategoryRaw: Int = SizeCategory.standard.rawValue

    // Embedded thumbnail data (PNG), synced. External storage keeps the row small.
    @Attribute(.externalStorage)
    var thumbnailData: Data?

    // Synced original image bytes (external storage -> CKAsset under the hood when CloudKit is enabled)
    @Attribute(.externalStorage)
    var originalImageData: Data?

    // File URL to original image stored on disk (local cache only, not synced)
    @Transient
    var imageFileURL: URL?
    
    // Work-in-progress map/drawing data (synced, but separate from finalized originalImageData)
    // This allows users to continue editing across devices without losing work
    @Attribute(.externalStorage)
    var draftMapWorkData: Data?
    
    // Timestamp of last draft save (helps determine if draft is current)
    var draftMapWorkTimestamp: Date?
    
    // Map creation method used for the draft (stored as raw string for CloudKit compatibility)
    var draftMapMethodRaw: String?
    
    // Wizard step where the user left off (stored as raw string for CloudKit compatibility)
    var draftMapWizardStepRaw: String?

    // MARK: - AI Image Generation Metadata (ER-0009)
    // Added in AppSchemaV5 (CloudKit auto-migrates)

    /// Whether the card's image was generated by AI
    var imageGeneratedByAI: Bool? = nil

    /// AI provider used to generate the image (e.g., "Apple Intelligence", "OpenAI")
    var imageAIProvider: String? = nil

    /// Original prompt used to generate the image
    var imageAIPrompt: String? = nil

    /// Timestamp when the image was generated
    var imageAIGeneratedAt: Date? = nil

    // MARK: - Timeline System Properties (ER-0008)
    // Optional properties - CloudKit auto-migrates without explicit schema migration

    /// Calendar system used by this timeline (for Timeline cards only)
    /// Optional relationship to CalendarSystem model
    @Relationship(deleteRule: .nullify)
    var calendarSystem: CalendarSystem? = nil

    /// Epoch date - the starting point/zero-date for this timeline
    /// For Timeline cards only. Defines when the timeline begins.
    var epochDate: Date? = nil

    /// Human-readable description of the epoch
    /// Example: "The beginning of the Age of Starlight", "Year 0 of the Empire"
    var epochDescription: String? = nil

    /// Reference to calendar system (for kind=.calendars only)
    /// CloudKit: Optional, defaults to nil
    @Relationship(deleteRule: .cascade, inverse: \CalendarSystem.calendarCard)
    var calendarSystemRef: CalendarSystem?

    // Precomputed aggregate for simple/backup searches
    // Provide a default so migration can backfill existing rows.
    var normalizedSearchText: String = ""

    // Many-to-many with StructureElement (CloudKit: relationships must be optional; inverse is declared on StructureElement)
    @Relationship(deleteRule: .nullify)
    var structureElements: [StructureElement]? = []

    // Inverse collections for CardEdge (CloudKit: relationships must be optional)
    @Relationship(deleteRule: .cascade, inverse: \CardEdge.from)
    var outgoingEdges: [CardEdge]? = []

    @Relationship(deleteRule: .cascade, inverse: \CardEdge.to)
    var incomingEdges: [CardEdge]? = []

    // Inverse collection for Citation.card
    @Relationship(deleteRule: .cascade, inverse: \Citation.card)
    var citations: [Citation]? = []

    // New: Inverse relationships for Board and BoardNode (CloudKit requires declared inverses)
    // Boards where this card is the primaryCard. Deleting the card nullifies primaryCard on those boards.
    var primaryBoards: [Board]? = []

    // All BoardNode placements that reference this card. Deleting the card should remove those nodes.
    @Relationship(deleteRule: .cascade, inverse: \BoardNode.card)
    var boardNodes: [BoardNode]? = []

    init(
        id: UUID = UUID(),
        kind: Kinds = .projects,
        name: String,
        subtitle: String,
        detailedText: String,
        author: String? = nil,
        sizeCategory: SizeCategory = .standard,
        thumbnailData: Data? = nil,
        originalImageData: Data? = nil,
        imageFileURL: URL? = nil
    ) {
        self.id = id
        self.kindRaw = kind.rawValue
        self.name = name
        self.subtitle = subtitle
        self.detailedText = detailedText
        self.author = author
        self.sizeCategoryRaw = sizeCategory.rawValue
        self.thumbnailData = thumbnailData
        self.originalImageData = originalImageData
        self.imageFileURL = imageFileURL
        self.normalizedSearchText = ""
        recomputeNormalizedSearchText()
    }

    // Computed Kind (backed by kindRaw)
    var kind: Kinds {
        Kinds(rawValue: kindRaw) ?? .projects
    }

    // Computed SizeCategory (backed by sizeCategoryRaw)
    var sizeCategory: SizeCategory {
        get { SizeCategory(rawValue: sizeCategoryRaw) ?? .standard }
        set { sizeCategoryRaw = newValue.rawValue }
    }

    // Convenience check for Calendar cards
    var isCalendarCard: Bool {
        kind == .calendars
    }

    var thumbnailURL: URL? {
        // If we have thumbnail data, create a data URL
        guard let data = thumbnailData else { return nil }
        return URL(string: "data:image/png;base64,\(data.base64EncodedString())")
    }
}

// MARK: - SwiftUI Images

extension Card {
    @available(*, deprecated, message: "Use makeImage() async to avoid main-thread decoding")
    var image: Image? {
        guard let cg = cgImageFromFileURL() else { return nil }
        return Image(decorative: cg, scale: 1, orientation: .up)
    }

    @available(*, deprecated, message: "Use makeThumbnailImage() async to avoid main-thread decoding")
    var thumbnailImage: Image? {
        guard let cg = cgImageFromThumbnailData() ?? cgImageFromFileURL() else { return nil }
        return Image(decorative: cg, scale: 1, orientation: .up)
    }

    func makeThumbnailImage() async -> Image? {
        guard let cg = await loadThumbnailCGImage() else { return nil }
        return Image(decorative: cg, scale: 1, orientation: .up)
    }

    func makeImage() async -> Image? {
        guard let cg = await loadFullCGImage() else { return nil }
        return Image(decorative: cg, scale: 1, orientation: .up)
    }

    func prefetchImages() {
        Task.detached(priority: .utility) { [weak self] in
            guard let self else { return }
            _ = await loadThumbnailCGImage()
            _ = await loadFullCGImage()
        }
    }
}

// MARK: - Public Mutators

extension Card {
    func setOriginalImageData(_ data: Data, preferredFileExtension: String? = nil) throws {
        let inferredExt = Self.inferFileExtension(from: data) ?? "jpg"
        let ext = (preferredFileExtension?.lowercased()).flatMap { $0.isEmpty ? nil : $0 } ?? inferredExt

        // Update synced original first so we always have a copy in the database/CloudKit
        self.originalImageData = data

        // Replace local cache file
        if let oldURL = imageFileURL {
            try? ImageStore.shared.deleteOriginalImage(at: oldURL)
        }
        let fileURL = try ImageStore.shared.writeOriginalImageData(data, for: id, fileExtension: ext)
        self.imageFileURL = fileURL

        // Build/refresh thumbnail + caches
        if let cg = Self.makeCGImage(from: data) {
            self.thumbnailData = Self.makePNGThumbnailData(from: cg, maxPixel: Self.thumbnailMaxPixel)
            Self.cache(set: cg, for: cacheKeyFull)
            if let thumbCG = Self.makeCGImage(from: self.thumbnailData ?? Data()) {
                Self.cache(set: thumbCG, for: cacheKeyThumb)
            } else {
                if let scaled = Self.makeScaledCGImage(from: cg, maxPixel: Self.thumbnailMaxPixel) {
                    Self.cache(set: scaled, for: cacheKeyThumb)
                }
            }
        } else {
            // Fallback: try reading back from the cache file we just wrote
            if let cg = cgImageFromFileURL() {
                self.thumbnailData = Self.makePNGThumbnailData(from: cg, maxPixel: Self.thumbnailMaxPixel)
                Self.cache(set: cg, for: cacheKeyFull)
                if let thumbCG = Self.makeCGImage(from: self.thumbnailData ?? Data()) {
                    Self.cache(set: thumbCG, for: cacheKeyThumb)
                }
            }
        }
    }

    func replaceOriginalImageData(_ data: Data, preferredFileExtension: String? = nil) throws {
        try setOriginalImageData(data, preferredFileExtension: preferredFileExtension)
    }

    func removeOriginalImage() {
        // Remove local cache file
        if let url = imageFileURL {
            try? ImageStore.shared.deleteOriginalImage(at: url)
        }
        imageFileURL = nil
        // Remove synced original and caches
        originalImageData = nil
        Self.cache(removeFor: cacheKeyFull)
    }

    func regenerateThumbnailFromOriginal() {
        // Prefer local file; fall back to synced original data
        if let cg = cgImageFromFileURL() {
            self.thumbnailData = Self.makePNGThumbnailData(from: cg, maxPixel: Self.thumbnailMaxPixel)
        } else if let data = originalImageData, let cg = Self.makeCGImage(from: data) {
            self.thumbnailData = Self.makePNGThumbnailData(from: cg, maxPixel: Self.thumbnailMaxPixel)
        } else {
            self.thumbnailData = nil
        }

        if let thumbCG = Self.makeCGImage(from: self.thumbnailData ?? Data()) {
            Self.cache(set: thumbCG, for: cacheKeyThumb)
        } else if let fullCG = Self.cache(get: cacheKeyFull) {
            if let scaled = Self.makeScaledCGImage(from: fullCG, maxPixel: Self.thumbnailMaxPixel) {
                Self.cache(set: scaled, for: cacheKeyThumb)
            }
        }
    }

    @discardableResult
    func validateOriginalURL() -> Bool {
        guard let url = imageFileURL else { return false }
        guard ImageStore.shared.isURLInsideStore(url) else {
            return FileManager.default.fileExists(atPath: url.path)
        }
        let exists = FileManager.default.fileExists(atPath: url.path)
        if !exists {
            imageFileURL = nil
            Self.cache(removeFor: cacheKeyFull)
        }
        return exists
    }

    // Updated: accept a context and perform safe, context-local cleanup of related rows.
    func cleanupBeforeDeletion(in ctx: ModelContext) {
        // 1) Image/caches first (purely local)
        removeOriginalImage()
        clearImageCaches()

        // 2) Purge BoardNodes that reference this Card (context-local fetch by ID)
        let myID = self.id
        do {
            var nodeFetch = FetchDescriptor<BoardNode>(
                predicate: #Predicate { $0.card?.id == myID }
            )
            nodeFetch.fetchLimit = 0
            let nodes = try ctx.fetch(nodeFetch)
            for n in nodes {
                ctx.delete(n)
            }
        } catch {
            // Best-effort; continue
        }

        // 3) Nullify any Boards where this card is set as primaryCard
        do {
            var boardFetch = FetchDescriptor<Board>(
                predicate: #Predicate { $0.primaryCard?.id == myID }
            )
            boardFetch.fetchLimit = 0
            let boards = try ctx.fetch(boardFetch)
            for b in boards {
                b.primaryCard = nil
            }
        } catch {
            // continue
        }

        // 4) Purge CardEdges where this Card is either endpoint (by ID)
        do {
            var edgeFetch = FetchDescriptor<CardEdge>(
                predicate: #Predicate { $0.from?.id == myID || $0.to?.id == myID }
            )
            edgeFetch.fetchLimit = 0
            let edges = try ctx.fetch(edgeFetch)
            for e in edges {
                ctx.delete(e)
            }
        } catch {
            // continue
        }

        // 5) Save if anything changed (best-effort)
        try? ctx.save()
    }

    func clearImageCaches() {
        Self.cache(removeFor: cacheKeyFull)
        Self.cache(removeFor: cacheKeyThumb)
    }

    static func purgeAllImageCaches() {
        cgImageCache.removeAllObjects()
    }
    
    // MARK: - Draft Map Work Management
    
    /// Save work-in-progress map/drawing data
    /// - Parameters:
    ///   - data: The serialized drawing/map data
    ///   - method: The map creation method being used
    ///   - wizardStep: The wizard step where the user left off
    func saveDraftMapWork(_ data: Data, method: String, wizardStep: String? = nil) {
        self.draftMapWorkData = data
        self.draftMapWorkTimestamp = Date()
        self.draftMapMethodRaw = method
        self.draftMapWizardStepRaw = wizardStep
    }
    
    /// Check if there is unsaved draft work
    var hasDraftMapWork: Bool {
        return draftMapWorkData != nil && !draftMapWorkData!.isEmpty
    }
    
    /// Clear the draft map work (typically called after finalizing)
    func clearDraftMapWork() {
        self.draftMapWorkData = nil
        self.draftMapWorkTimestamp = nil
        self.draftMapMethodRaw = nil
        self.draftMapWizardStepRaw = nil
    }
    
    /// Get the age of the draft work (nil if no draft exists)
    var draftMapWorkAge: TimeInterval? {
        guard let timestamp = draftMapWorkTimestamp else { return nil }
        return Date().timeIntervalSince(timestamp)
    }
}

// MARK: - Image decoding/encoding helpers (internal access for cross-file use)

extension Card {
    // Decode a CGImage from raw image data (PNG, JPEG, etc.)
    static func makeCGImage(from data: Data) -> CGImage? {
        guard let src = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        return CGImageSourceCreateImageAtIndex(src, 0, nil)
    }

    // Read CGImage directly from the file URL (internal for cross-file use)
    func cgImageFromFileURL() -> CGImage? {
        guard let url = imageFileURL else { return nil }
        guard let src = CGImageSourceCreateWithURL(url as CFURL, nil) else { return nil }
        return CGImageSourceCreateImageAtIndex(src, 0, nil)
    }

    // Produce a PNG thumbnail Data by scaling to fit within maxPixel
    static func makePNGThumbnailData(from cg: CGImage, maxPixel: Int) -> Data? {
        // Scale first (self-contained; does not rely on private helpers)
        let w = cg.width
        let h = cg.height
        let maxDim = max(w, h)
        let scale = maxDim > maxPixel ? CGFloat(maxPixel) / CGFloat(maxDim) : 1.0
        let targetW = max(1, Int(CGFloat(w) * scale))
        let targetH = max(1, Int(CGFloat(h) * scale))

        guard let colorSpace = cg.colorSpace ?? CGColorSpace(name: CGColorSpace.sRGB) else { return nil }
        guard let ctx = CGContext(
            data: nil,
            width: targetW,
            height: targetH,
            bitsPerComponent: 8,
            bytesPerRow: 0,
            space: colorSpace,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { return nil }

        ctx.interpolationQuality = .high
        ctx.draw(cg, in: CGRect(x: 0, y: 0, width: targetW, height: targetH))
        guard let scaled = ctx.makeImage() else { return nil }

        // Encode PNG
        let data = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(data, UTType.png.identifier as CFString, 1, nil) else { return nil }
        CGImageDestinationAddImage(dest, scaled, nil)
        guard CGImageDestinationFinalize(dest) else { return nil }
        return data as Data
    }
}

// MARK: - Image decoding/encoding helpers (private internals)

private extension Card {
    static let thumbnailMaxPixel: Int = 256

    private static let cgImageCache: NSCache<NSString, CGImage> = {
        let c = NSCache<NSString, CGImage>()
        c.countLimit = 500
        return c
    }()

    var cacheKeyFull: String {
        "\(id.uuidString)-full"
    }

    var cacheKeyThumb: String {
        let v = thumbnailData?.count ?? 0
        return "\(id.uuidString)-thumb-\(v)"
    }

    static func cache(get key: String) -> CGImage? {
        cgImageCache.object(forKey: key as NSString)
    }

    static func cache(set image: CGImage, for key: String) {
        cgImageCache.setObject(image, forKey: key as NSString)
    }

    static func cache(removeFor key: String) {
        cgImageCache.removeObject(forKey: key as NSString)
    }

    func loadThumbnailCGImage() async -> CGImage? {
        if let cached = Self.cache(get: cacheKeyThumb) {
            return cached
        }

        if let data = thumbnailData {
            if let cg = await Self.decodeCGImageAsync(fromData: data) {
                Self.cache(set: cg, for: cacheKeyThumb)
                return cg
            }
        }

        // Derive from full image (local cache or synced original)
        guard let original = await loadFullCGImage() else { return nil }
        if let scaled = Self.makeScaledCGImage(from: original, maxPixel: Self.thumbnailMaxPixel) {
            Self.cache(set: scaled, for: cacheKeyThumb)
            return scaled
        }
        return nil
    }

    func loadFullCGImage() async -> CGImage? {
        if let cached = Self.cache(get: cacheKeyFull) {
            return cached
        }

        // Try local cache file first
        if let url = imageFileURL, let cg = await Self.decodeCGImageAsync(fromURL: url) {
            Self.cache(set: cg, for: cacheKeyFull)
            return cg
        }

        // Fall back to synced original data
        if let data = originalImageData, let cg = await Self.decodeCGImageAsync(fromData: data) {
            Self.cache(set: cg, for: cacheKeyFull)

            // Opportunistically reconstruct the local cache file for faster subsequent loads
            if imageFileURL == nil {
                let ext = Self.inferFileExtension(from: data) ?? "jpg"
                if let fileURL = try? await ImageStore.shared.writeOriginalImageData(data, for: id, fileExtension: ext) {
                    imageFileURL = fileURL
                }
            }
            return cg
        }

        return nil
    }

    static func decodeCGImageAsync(fromData data: Data) async -> CGImage? {
        await withCheckedContinuation { continuation in
            Task.detached(priority: .utility) {
                let cg = makeCGImage(from: data)
                continuation.resume(returning: cg)
            }
        }
    }

    static func decodeCGImageAsync(fromURL url: URL) async -> CGImage? {
        await withCheckedContinuation { continuation in
            Task.detached(priority: .utility) {
                guard let src = CGImageSourceCreateWithURL(url as CFURL, nil) else {
                    continuation.resume(returning: nil)
                    return
                }
                let cg = CGImageSourceCreateImageAtIndex(src, 0, nil)
                continuation.resume(returning: cg)
            }
        }
    }

    func cgImageFromThumbnailData() -> CGImage? {
        guard let data = thumbnailData as CFData? else { return nil }
        guard let src = CGImageSourceCreateWithData(data, nil) else { return nil }
        return CGImageSourceCreateImageAtIndex(src, 0, nil)
    }

    static func makeScaledCGImage(from cg: CGImage, maxPixel: Int) -> CGImage? {
        let w = cg.width
        let h = cg.height
        let maxDim = max(w, h)
        let scale = maxDim > maxPixel ? CGFloat(maxPixel) / CGFloat(maxDim) : 1.0
        let targetW = max(1, Int(CGFloat(w) * scale))
        let targetH = max(1, Int(CGFloat(h) * scale))

        guard let colorSpace = cg.colorSpace ?? CGColorSpace(name: CGColorSpace.sRGB) else { return nil }
        guard let ctx = CGContext(
            data: nil,
            width: targetW,
            height: targetH,
            bitsPerComponent: 8,
            bytesPerRow: 0,
            space: colorSpace,
            bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
        ) else { return nil }

        ctx.interpolationQuality = .high
        ctx.draw(cg, in: CGRect(x: 0, y: 0, width: targetW, height: targetH))
        return ctx.makeImage()
    }

    static func inferFileExtension(from data: Data) -> String? {
        guard let src = CGImageSourceCreateWithData(data as CFData, nil),
              let type = CGImageSourceGetType(src) as String?,
              let utType = UTType(type) else {
            return nil
        }
        return utType.preferredFilenameExtension
    }
}

// MARK: - Transferable Support for Drag & Drop

extension Card {
    // Create a sendable transfer representation for the card
    func createTransferRepresentation() -> CardTransferData {
        CardTransferData(
            id: self.id,
            name: self.name,
            kindRaw: self.kindRaw
        )
    }
}

// Make CardTransferData itself Transferable instead of Card
extension CardTransferData: Transferable {
    static var transferRepresentation: some TransferRepresentation {
        DataRepresentation(contentType: .cardReference) { cardData in
            try JSONEncoder().encode(cardData)
        } importing: { data in
            try JSONDecoder().decode(CardTransferData.self, from: data)
        }
    }
}

// Transfer data structure for drag operations
struct CardTransferData: Sendable {
    let id: UUID
    let name: String
    let kindRaw: String
}

// Explicitly nonisolated Codable conformance to avoid main actor isolation issues
extension CardTransferData: Codable {
    nonisolated init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decode(UUID.self, forKey: .id)
        self.name = try container.decode(String.self, forKey: .name)
        self.kindRaw = try container.decode(String.self, forKey: .kindRaw)
    }
    
    nonisolated func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(kindRaw, forKey: .kindRaw)
    }
    
    private enum CodingKeys: String, CodingKey {
        case id, name, kindRaw
    }
}

// Custom UTType for card references
extension UTType {
    // Avoid Info.plist registration; use a failable initializer with a safe fallback.
    static let cardReference: UTType = UTType("com.cumberland.card-reference") ?? .json
}

// MARK: - Search normalization

private extension Card {
    func recomputeNormalizedSearchText() {
        let s = [name, subtitle, detailedText, author ?? ""]
            .joined(separator: " ")
            .folding(options: [.diacriticInsensitive, .caseInsensitive], locale: .current)
            .lowercased()
        normalizedSearchText = s
    }
}

// MARK: - SizeCategory

enum SizeCategory: Int, Codable, CaseIterable, Hashable, Sendable {
    case compact
    case standard
    case large

    var displayName: String {
        switch self {
        case .compact:  return "Compact"
        case .standard: return "Standard"
        case .large:    return "Large"
        }
    }
}
